### ISSUE TITLE
EMPRESA DITRANSA 

### ISSUE THREAD

**Issue by camilafcubillos** [Anamontesf/GiroZero-GPS-#16]
Se requiere LINK o datos procesados de la empresa DITRANSA

Se dejan los archivos revisados en la dirección:
GiroZeroGPS / DITRANSA/ 2. DATOS REVISADOS/2. DATOS HASTA 11-05-2023
Se deja la información de las placas (ficha de entrada de datos) en el Excel en la dirección:
GiroZeroGPS / DITRANSA/ 2. DATOS REVISADOS/1. INFORMACION PLACAS/ DITRANSA TRAZABILIDAD

Se requiere el tablero y fichas de salida para el día 30 de mayo del 2023, con el fin de reportar a externos.

La estructura de las carpetas es de este modo:
NOMBRE DE LA EMPRESA
1. DATOS BRUTOS
2. DATOS REVISADOS
1. INFORMACIÓN PLACAS
NOMBRE DE LA EMPRESA_TRAZABILIDAD
2. DATOS HASTA 11-05-2023
3. DATOS PROCESADOS

**Comment by Eduardo-Encina** [comment]
1. **Link Tableau Public:** https://public.tableau.com/app/profile/coltanques @AndresFelipeRey 
2. Los _datos procesados_ y la _ficha de salida_ se encuentra en la **carpeta DATOS PROCESADOS**

**Comment by Anamontesf** [comment]
Se reviso cada uno de los dashboards teniendo en cuenta los siguientes criterios:

1. La información generada en la revisión por parte de giro zero, la cual incluye temporalidad y tiene asociada la cantidad de vehiculos por mes. 
2. Interpretaciones logicas y estadisticas de los graficos y reportes.

Se valida que la información se encuentra dentro de los margenes logicos y corresponde a la información de GPS suministrada por las empresas, adicionalmente se tienen los siguientes comentarios especificos.

- En el dashboard de la Velocidad de red vial o Stage 2 encontramos que el filtro de la fecha no se actualiza con el mes a la hora de realizar los filtros, por favor revisar este problema.
- El dashboard de Relanti en la información operacional cuando se tienen seleccinados todos los meses no muestra la totalidad de vehiculos solo toma la cota mayor de los meses evaluados.
-En general consideramos que para lograr una mejor interpretación inferencial de la información de todos los tableros es necesario que se conozca el numero de vehiculos asociados al mes filtrado lo cual solo ocurre para uno de los tableros, como se encuentran en este momento solo con el numero de registros o puntos para algunos de ellos puede generar confusiones y ruido en el analisis, por lo cual consideramos que esto mejoraria sustancialmente la interpretación de los tableros por parte de los usuarios.

Adjuntamos el link al archivo con nuestros resultados, los cuales fueron empleados para la revisión.

https://uniandes.sharepoint.com/:x:/r/sites/UKPACT-GiroZero-GiroZeroGPS/_layouts/15/Doc.aspx?sourcedoc=%7B3016414A-DA1F-44A9-8050-008D3FABA327%7D&file=DITRANSA%20TRAZABILIDAD_code.xlsx&action=default&mobileredirect=true

@Eduardo-Encina Revisar si podemos aplicar los comentarios para cerrar el issue y que @camilafcubillos pueda compartir la información con los usuarios externos.

**Comment by Eduardo-Encina** [comment]
A continuación, mis comentarios:

1. El dashboard "Velocidad de Red Vial" fue corregido y subido a Tableau Public.

2. La cantidad de vehículos moniteoreados para la empresa Ditransa son **23 vehículos**. El dashboars muestra la cantidad correcta de vehículos (validar con planilla de salida). 
Recordar que los dashboard muestra la cantidad de vehículos únicos, por lo tanto si, por ejemplo, en enero son 11 vehículos y marzo son 9 vehículos, eso no quiere decir que el total sean 20 vehículos. (Pueden haber vehículos que esten presenten en ambos meses).
En definitiva no se observa inconveniente en este dashboard.

3.  Se corrige el dashboard de ralentí, y ahora visualiza los meses de enero y febrero 2022.

**Comment by Anamontesf** [comment]
Se generaron las estadisticas finales para
[ESTADISTICAS PROCESAMIENTO DATOS (DITRANSA).xlsx](https://github.com/Anamontesf/GiroZero-GPS-/files/11899100/ESTADISTICAS.PROCESAMIENTO.DATOS.DITRANSA.xlsx)
Modificaciones revisadas y aprobadas. 
Todo listo para compartir con la empresa.

**Comment by HelmuthRaddatz** [comment]
La data cuenta con procesamiento hasta el 31/03/2023. La última actualización fue el 6 de junio del 2023. Se puede visualizar en: https://public.tableau.com/app/profile/ditransa. Confirmar que esté correcto. @Anamontesf @camilafcubillos

**Comment by Anamontesf** [comment]
Esta todo ok con esta empresa.
