### ISSUE TITLE
C&S LOGISTICA

### ISSUE THREAD

**Issue by Anamontesf** [Anamontesf/GiroZero-GPS-#27]
Se encuentra la información organizada y filtrada con el respectivo archivo de reporte de resultados: 

https://uniandes.sharepoint.com/:x:/r/sites/UKPACT-GiroZero-GiroZeroGPS/_layouts/15/Doc.aspx?action=edit&sourcedoc=%7Beca7a05e-6b49-4962-b1b0-9fb6b7f028b7%7D&wdOrigin=TEAMS-ELECTRON.teamsSdk.openFilePreview&wdExp=TEAMS-CONTROL&web=1

La estructura de las carpetas se encuentra de este modo:
NOMBRE DE LA EMPRESA (C&S Logistica)

1.DATOS BRUTOS
2.DATOS REVISADOS (Contiene nuestro excel con la revision realizada y los archivos debidamente filtrados)
3.DATOS PROCESADOS

Se requiere el tablero y fichas de salida para el día 27 de junio del 2023, con el fin revisar los output, validar el funcionamiento de los protocolos y reportar resultados a externos.

**Comment by Eduardo-Encina** [comment]
Hola, el proceso de actualización de datos de la empresa **CYS** está finalizado:

- Los datos procesados y la ficha de salida se encuentra en la carpeta **DATOS PROCESADOS**
- **Link dashboard's:** 
https://public.tableau.com/app/profile/reportes.cys

**Comment by camilafcubillos** [comment]
Conforme a las placas faltantes estas:

FALTAN   PLACAS EN EMISIONES CO2 UFQ882- WLJ950 - SXG014 - LKK050- SSZ555 -  TGY865-WBG169- WLB951-WLC040 , cumplen con los formatos pero no se tienen en cuenta en los tableros. 

@Eduardo-Encina

**Comment by HelmuthRaddatz** [comment]
Las placas UFQ882, WLJ950, SXG014 no se encuentran en los datos GPS compartidos en https://uniandes.sharepoint.com/sites/UKPACT-GiroZero-GiroZeroGPS/Documentos%20compartidos/Forms/AllItems.aspx?fromShare=true&ga=1&id=%2Fsites%2FUKPACT%2DGiroZero%2DGiroZeroGPS%2FDocumentos%20compartidos%2FGiroZero%20GPS%2FC%26S%20LOGISTICA%2F1%2E%20DATOS%20BRUTOS%2F1%2E%20DATOS%20BRUTOS%20HASTA%2011%2D05%2D2023&viewid=de89fbdc%2Dbc05%2D4a86%2Db3f5%2D5bb121022029. @Anamontesf @camilafcubillos 
Las placas: LKK050, SSZ555, TGY865, WBG169, WLB951, WLC040, si se encuentran, por lo que se revisará junto a @AngeloValenzuelaP para su procesamiento nuevamente.

**Comment by Anamontesf** [comment]
En la revision se encontro que no se han incluido estas placas ni en los tableros, ni en el archivo de trazabilidad: LKK050, SSZ555, TGY865, WBG169, WLB951, WLC040. 

https://uniandes.sharepoint.com/:x:/r/sites/UKPACT-GiroZero-GiroZeroGPS/_layouts/15/Doc.aspx?action=edit&sourcedoc=%7B9096442f-f3f2-4b6a-b6c1-2582cb389bca%7D&wdOrigin=TEAMS-ELECTRON.teamsSdk.openFilePreview&wdExp=TEAMS-CONTROL&web=1

Adicionalmente se observa NULL en el filtro de mes en el tablero de CO2

**Comment by HelmuthRaddatz** [comment]
Estimada @Anamontesf, al momento de revisar la data subida a la plataforma de Sharepoint para las placas patentes indicadas, estas se encuentran fuera del periodo de procesamiento de los datos, es decir, posterior al 13 de marzo del 2024. Por esta razón, no fueron procesados, en caso de requerir su procesamiento, se deberá hablar y cerrar mediante otro proyecto con Julio Villalobos.

Por otro lado, ya se ha corregido la situación con los NULL que aparecen en ese tablero, sin embargo, quiero recalcar que aquellos registros que se encuentran **fuera del área de estudio**, no figurarán en el tablero y por ende, la cantidad de data que se visualiza sin los registros NULL se ve afectada. Se puede visualizar en el siguiente enlace: https://public.tableau.com/app/profile/reportes.cys/viz/EMISIONESCO2_16685388498170/EMISIONESCO2
