### ISSUE TITLE
COTRANSCOL 

### ISSUE THREAD

**Issue by camilafcubillos** [Anamontesf/GiroZero-GPS-#28]
Se encuentra la información organizada y filtrada con el respectivo archivo de reporte de resultados:

https://uniandes.sharepoint.com/:f:/r/sites/UKPACT-GiroZero-GiroZeroGPS/Documentos%20compartidos/GiroZero%20GPS/COTRANSCOL/2.%20DATOS%20REVISADOS?csf=1&web=1&e=CayBQS

La estructura de las carpetas se encuentra de este modo:
NOMBRE DE LA EMPRESA (COTRANSCOL) 

1.DATOS BRUTOS
2.DATOS REVISADOS (Contiene nuestro excel con la revision realizada y los archivos debidamente filtrados)
3.DATOS PROCESADOS

Se requiere el tablero y fichas de salida para el día 17 de julio del 2023, con el fin revisar los output, validar el funcionamiento de los protocolos y reportar resultados a externos.

**Comment by Eduardo-Encina** [comment]
Hola, el proceso de actualización de los dashboard's de la empresa **COTRANSCOL** se encuentra finalizado:

- Los datos procesados y la ficha de salida se encuentra en la carpeta DATOS PROCESADOS
- Link dashboard's: https://public.tableau.com/app/profile/reportes.cotranscol

**Comment by Anamontesf** [comment]
Se revisaron los tableros de la empresa y se tiene el siguiente comentario:

- En las estadisticas que levantamos de los datos brutos el conteo nos daba que ningun vehiculo ni registro tenia velocidad 0, lo cual se evidencia en los tableros de velocidad, pero nos gustaria aclarar porque se encuentran entonces 104 vehiculos en el tablero de relanti. @Eduardo-Encina

**Comment by Eduardo-Encina** [comment]
Hola, el proceso de actualización de los dashboard's de la empresa **COTRANSCOL** se encuentra finalizado:

- Link dashboard's: https://public.tableau.com/app/profile/reportes.cotranscol

**Comment by camilafcubillos** [comment]
Se encuentra la información de Agosto de 2023 para COTRANCOL en la siguiente carpeta 

https://uniandes.sharepoint.com/:f:/r/sites/UKPACT-GiroZero-GiroZeroGPS/Documentos%20compartidos/GiroZero%20GPS/COTRANSCOL/2.%20DATOS%20REVISADOS/5.%20DATOS%20AGOSTO%202023%20(P)?csf=1&web=1&e=5ExhNe 

Y en la hoja nombrada 4TA FICHA COTRANSCOL se encuentran las placas compartidas 
https://uniandes.sharepoint.com/:x:/r/sites/UKPACT-GiroZero-GiroZeroGPS/Documentos%20compartidos/GiroZero%20GPS/COTRANSCOL/2.%20DATOS%20REVISADOS/1.%20INFORMACION%20PLACAS/COTRANSCOL%20TRAZABILIDAD.xlsx?d=w56e7416a0477401fb609a9af7023b841&csf=1&web=1&e=Shdfy9 


Se necesita actualizar el link del tablero GPS.

**Comment by HelmuthRaddatz** [comment]
Los datos se encuentran procesados y publicados. Se pueden visualizar en: https://public.tableau.com/app/profile/reportes.cotranscol

**Comment by camilafcubillos** [comment]
En el tablero de emisiones de CO2 aparece null, si se desmarca los valores no son razonables, a que se debe o que se le atribuye el null? o que contiene el null, dado que no sabemos, por favor aclarar o corregir dado sea el caso. @HelmuthRaddatz @AngeloValenzuelaP 

@Anamontesf SE SUBEN los datos para revisión de ENERO, FEBRERO, MARZO del 2024 de cotranscol en las siguientes carpetas https://uniandes.sharepoint.com/:f:/r/sites/UKPACT-GiroZero-GiroZeroGPS/Documentos%20compartidos/GiroZero%20GPS/COTRANSCOL/1.%20DATOS%20BRUTOS/6.%20DATOS%20ENERO%20y%20FEBRERO%202024%20PENDIENTE?csf=1&web=1&e=fVvdsn y https://uniandes.sharepoint.com/:f:/r/sites/UKPACT-GiroZero-GiroZeroGPS/Documentos%20compartidos/GiroZero%20GPS/COTRANSCOL/1.%20DATOS%20BRUTOS/7.%20DATOS%20MARZO%202024%20PENDIENTE?csf=1&web=1&e=zG7iDl La ficha de entrada se encuentra en el siguiente link, en la hoja COTRANSCOL 5TA FICHA https://uniandes.sharepoint.com/:x:/r/sites/UKPACT-GiroZero-GiroZeroGPS/Documentos%20compartidos/GiroZero%20GPS/COTRANSCOL/2.%20DATOS%20REVISADOS/1.%20INFORMACION%20PLACAS/COTRANSCOL%20TRAZABILIDAD.xlsx?d=w56e7416a0477401fb609a9af7023b841&csf=1&web=1&e=VFLRa7

**Comment by Anamontesf** [comment]
En la revision del tablero de CO2 se encontro que persiste el error del NULL en el filtro de selección de vehiculo, en el mes y en el dia. Por otro lado no esta el mes de agosto que si aparece en el tablero de Ralenti y de velocidad de operación.

Adicionalmente no se encuentra el archivo de trazabilidad de las estadisticas en teams @HelmuthRaddatz

**Comment by HelmuthRaddatz** [comment]
Estimada @Anamontesf, se ha reparado la situación del NULL en el filtro de selección de vehículo para el tablero de Emisiones CO2, de igual forma se corrigió el mes de agosto: https://public.tableau.com/app/profile/reportes.cotranscol/viz/EmisionesCO2_16897829089000/EMISIONESCO2?publish=yes.

**Comment by camilafcubillos** [comment]
COMENTARIO : para @camilafcubillos.

Datos pendientes de cotranscol hasta 5 de agosto del 2024 (enero a julio del 2024) (datos nuevos, fuera de tiempo de acuerdos)

https://uniandes.sharepoint.com/:f:/r/sites/UKPACT-GiroZero-GiroZeroGPS/Documentos%20compartidos/GiroZero%20GPS/COTRANSCOL/1.%20DATOS%20BRUTOS/6.%20DATOS%20ENERO%20y%20FEBRERO%202024%20PENDIENTE?csf=1&web=1&e=w293LD

https://uniandes.sharepoint.com/:f:/r/sites/UKPACT-GiroZero-GiroZeroGPS/Documentos%20compartidos/GiroZero%20GPS/COTRANSCOL/1.%20DATOS%20BRUTOS/7.%20DATOS%20MARZO%202024%20PENDIENTE?csf=1&web=1&e=otifQH

https://uniandes.sharepoint.com/:f:/r/sites/UKPACT-GiroZero-GiroZeroGPS/Documentos%20compartidos/GiroZero%20GPS/COTRANSCOL/1.%20DATOS%20BRUTOS/8.%20DATOS%20ABRIL,%20MAYO,%20JUNIO%202024%20PENDIENTE?csf=1&web=1&e=8UvhVn

https://uniandes.sharepoint.com/:f:/r/sites/UKPACT-GiroZero-GiroZeroGPS/Documentos%20compartidos/GiroZero%20GPS/COTRANSCOL/1.%20DATOS%20BRUTOS/9.%20DATOS%20JULIO%202024%20PENDIENTE?csf=1&web=1&e=gCM3tG
