### ISSUE TITLE
PLEXA

### ISSUE THREAD

**Issue by camilafcubillos** [Anamontesf/GiroZero-GPS-#29]
Se encuentra la información organizada y filtrada con el respectivo archivo de reporte de resultados:

https://uniandes.sharepoint.com/:f:/r/sites/UKPACT-GiroZero-GiroZeroGPS/Documentos%20compartidos/GiroZero%20GPS/PLEXA/2.%20DATOS%20REVISADOS?csf=1&web=1&e=erTIq1

La estructura de las carpetas se encuentra de este modo:
NOMBRE DE LA EMPRESA (PLEXA)

1.DATOS BRUTOS
2.DATOS REVISADOS (Contiene nuestro excel con la revision realizada y los archivos debidamente filtrados)
3.DATOS PROCESADOS

Se requiere el tablero y fichas de salida para el día 17 de julio del 2023, con el fin revisar los output, validar el funcionamiento de los protocolos y reportar resultados a externos.

**Comment by Eduardo-Encina** [comment]
Hola, el proceso de actualización de datos de la empresa **PLEXA** se encuentra finalizado:

Los datos procesados y la ficha de salida se encuentra en la carpeta DATOS PROCESADOS
Link dashboard's: https://public.tableau.com/app/profile/reportes.plexa

**Comment by Anamontesf** [comment]
El tablero de emisiones presenta NULL en el filtro de mes, dia y vehiculos @HelmuthRaddatz

**Comment by HelmuthRaddatz** [comment]
Estiamda @Anamontesf, se encuentra corregido el tablero: https://public.tableau.com/app/profile/reportes.plexa/viz/EMISIONESCO2_16571316652160/EMISIONESCO2.
