### ISSUE TITLE
TENARIS

### ISSUE THREAD

**Issue by camilafcubillos** [Anamontesf/GiroZero-GPS-#30]
Se encuentra la información organizada y filtrada con el respectivo archivo de reporte de resultados:

https://uniandes.sharepoint.com/:f:/r/sites/UKPACT-GiroZero-GiroZeroGPS/Documentos%20compartidos/GiroZero%20GPS/TENARIS/2.%20DATOS%20REVISADOS?csf=1&web=1&e=Cdxa8I

La estructura de las carpetas se encuentra de este modo:
NOMBRE DE LA EMPRESA (TENARIS)

1.DATOS BRUTOS
2.DATOS REVISADOS (Contiene nuestro excel con la revision realizada y los archivos debidamente filtrados)
3.DATOS PROCESADOS

Se requiere el tablero y fichas de salida para el día 17 de julio del 2023, con el fin revisar los output, validar el funcionamiento de los protocolos y reportar resultados a externos.

**Comment by HelmuthRaddatz** [comment]
Los datos se encuentran procesados y publicados. Se pueden visualizar en: https://public.tableau.com/app/profile/reportes.tenaris/vizzes

**Comment by Anamontesf** [comment]
En la revision se encontro que el tablero de emisiones de C02 no corresponde al formato de las demas empresas, no estan los indicadores desagregrados, parece ser un dashboard viejo, la verdad no estoy familiarizada con el... durante el tiempo que he trabajado en GPS el tablero ha tenido otro formato de presentacion de indicadores y otros campos. Adicionalmente las placas y fechas no corresponden a la empresa Tenaris, por favor revisar.

Adicionalmente no se tiene archivo de estadisticas preprocesamiento en teams @HelmuthRaddatz

**Comment by Anamontesf** [comment]
Adicionalmente los tableros de velocidad tambien tienen fechas que no corresponden a la empresa @HelmuthRaddatz

**Comment by HelmuthRaddatz** [comment]
Estimada @Anamontesf, el tablero de emisiones CO2 se encuentra disponible para su visualización en: https://public.tableau.com/app/profile/reportes.tenaris/viz/EMISIONESCO2_16702654355480/EMISIONESCO2?publish=yes.

**Comment by Anamontesf** [comment]
Segun la revision realizada se tienen las siguientes observaciones:

1. En el tablero de emisiones de CO2 aparece unicamente 1 placa de las 12 de la empresa.
![image](https://github.com/user-attachments/assets/2634aedd-f447-4224-9e85-9add540ed12d)


3. En el tablero de velocidad de operacion aparecen datos desde enero hasta diciembre y esta empresa solo tiene datos de OCTUBRE 2022, lo cual evidencia que no se soluciono el problema reportado desde el 7 de mayo referente a que los datos de los tableros actuales no corresponden a los de la empresa. 
![image](https://github.com/user-attachments/assets/0f10eeb6-28f4-4a69-8424-69126b11ea93)
