### ISSUE TITLE
POZUELO NICARAGUA

### ISSUE THREAD

**Issue by camilafcubillos** [Anamontesf/GiroZero-GPS-#31]
Se encuentra la información organizada y filtrada con el respectivo archivo de reporte de resultados:

https://uniandes.sharepoint.com/:f:/r/sites/UKPACT-GiroZero-GiroZeroGPS/Documentos%20compartidos/GiroZero%20GPS/POZUELO%20NICARAGUA/2.%20DATOS%20REVISADOS?csf=1&web=1&e=ygfZWp

La estructura de las carpetas se encuentra de este modo:
NOMBRE DE LA EMPRESA (POZUELO NICARAGUA)

1.DATOS BRUTOS
2.DATOS REVISADOS (Contiene nuestro excel con la revision realizada y los archivos debidamente filtrados)
3.DATOS PROCESADOS

IMPORTANTE: 1) Esta empresa es una filial de NUTRESA en NICARAGUA, por lo que, la latitud y longitud varian con respecto a Colombia, 2) el precio de los galones la empresa lo pidio que fuera en dolares, por lo que, se adjunta (copio link) en un Excel de como POZUELO compró el galón en dolares de manera mensual, https://uniandes.sharepoint.com/:x:/r/sites/UKPACT-GiroZero-GiroZeroGPS/Documentos%20compartidos/GiroZero%20GPS/POZUELO%20NICARAGUA/2.%20DATOS%20REVISADOS/Costo%20Diesel%20Nicaragua%202022-2023.xlsx?d=w3b2fa7b1e54640ff9ef87cde1d6f7d62&csf=1&web=1&e=QD14FB , para tener como referencia estos valores, sin embargo, si se considera que es mejor la historicidad de precios de alguna otra fuente para Nicaragua, pues se aplica la más conveniente. 

Se requiere el tablero y fichas de salida para el día 31 de julio del 2023, con el fin revisar los output, validar el funcionamiento de los protocolos y reportar resultados a externos.

**Comment by Eduardo-Encina** [comment]
Hola, el proceso de actualización de datos de la empresa **POZUELO NICARAGUA** se encuentra finalizado:

- Link dashboard's: https://public.tableau.com/app/profile/reportes.pozuelo

**Comment by camilafcubillos** [comment]
Se necesita actualización de tablero GPS:

Nuevos datos se encuentran en 
https://uniandes.sharepoint.com/:f:/r/sites/UKPACT-GiroZero-GiroZeroGPS/Documentos%20compartidos/GiroZero%20GPS/POZUELO%20NICARAGUA/2.%20DATOS%20REVISADOS/4.%20DATOS%20JULIO%202023%20PENDIENTE?csf=1&web=1&e=7Oi6fC

Y status de las placas se encuentran en la hoja bajo el nombre PZ 3RA ficha 
https://uniandes.sharepoint.com/:x:/r/sites/UKPACT-GiroZero-GiroZeroGPS/Documentos%20compartidos/GiroZero%20GPS/POZUELO%20NICARAGUA/2.%20DATOS%20REVISADOS/1.%20INFORMACION%20PLACAS/POZUELO%20NICARAGUA%20TRAZABILIDAD.xlsx?d=wca39be220e3447639d65044fc34b5781&csf=1&web=1&e=7WUIXH

@Eduardo-Encina

**Comment by camilafcubillos** [comment]
Se necesita trazabilidad y procesamiento de nuevos datos 

https://uniandes.sharepoint.com/:f:/r/sites/UKPACT-GiroZero-GiroZeroGPS/Documentos%20compartidos/GiroZero%20GPS/POZUELO%20NICARAGUA/1.%20DATOS%20BRUTOS/3.%20DATOS%20JULIO%202023%20PENDIENTE?csf=1&web=1&e=6lgcRH (JULIO 2023)

https://uniandes.sharepoint.com/:f:/r/sites/UKPACT-GiroZero-GiroZeroGPS/Documentos%20compartidos/GiroZero%20GPS/POZUELO%20NICARAGUA/1.%20DATOS%20BRUTOS/4.%20DATOS%20AGOSTO%202023%20PENDIENTE?csf=1&web=1&e=p0wDte (AGOSTO 2023)

https://uniandes.sharepoint.com/:f:/r/sites/UKPACT-GiroZero-GiroZeroGPS/Documentos%20compartidos/GiroZero%20GPS/POZUELO%20NICARAGUA/1.%20DATOS%20BRUTOS/5.%20DATOS%20SEPTIEMBRE%202023%20PENDIENTE?csf=1&web=1&e=KwnsYf (SEPTIEMBRE 2023)

**Comment by HelmuthRaddatz** [comment]
El Dashboard se encuentra actualizado en https://public.tableau.com/app/profile/reportes.pozuelo/vizzes

**Comment by camilafcubillos** [comment]
Los tableros tienen NULL, es un checkbox que esta marcado y cuando se desmarca los valores cambian de manera significativa, por favor modificar esto ( o indicar a que hace atribución ese checkbox null) , el NULL se ve presente en varios tableros y cuando se marca el checkbox cambia distancia, indicadores, etc, corregirlo, muchas gracias. 

Se necesita trazabilidad y procesamiento de nuevos datos, 
STATUS DE LAS PLACAS SE ENCUENTRAN EN EL SIGUIENTE LINK EN LA HOJA BAJO EL NOMBRE PN 4TA 
https://uniandes.sharepoint.com/:x:/r/sites/UKPACT-GiroZero-GiroZeroGPS/Documentos%20compartidos/GiroZero%20GPS/POZUELO%20NICARAGUA/2.%20DATOS%20REVISADOS/1.%20INFORMACION%20PLACAS/POZUELO%20NICARAGUA%20TRAZABILIDAD.xlsx?d=wca39be220e3447639d65044fc34b5781&csf=1&web=1&e=wZAbqt 

NUEVOS DATOS EN LA CARPETA DE DATOS REVISADOS EN EL SIGUIENTE LINK 
https://uniandes.sharepoint.com/:f:/r/sites/UKPACT-GiroZero-GiroZeroGPS/Documentos%20compartidos/GiroZero%20GPS/POZUELO%20NICARAGUA/2.%20DATOS%20REVISADOS/7.%20OCT-NOV-DIC%202023%20__%20ENERO%202024%20PENDIENTE?csf=1&web=1&e=Fa1lrE

@HelmuthRaddatz

**Comment by Anamontesf** [comment]
En la revision del tablero de CO2 se encontro que persiste el error del NULL en el filtro de selección de vehiculo, en el mes y en el dia. Por otro lado no esta el mes de agosto que si aparece en el tablero de Ralenti y de velocidad de operación.

Adicionalmente no se encuentra el archivo de trazabilidad de las estadisticas en teams @HelmuthRaddatz

**Comment by Anamontesf** [comment]
Este tablero es el más urgente de todos @HelmuthRaddatz  como te comentamos desde DICIEMBRE Y NUEVAMENTE EN ENERO es la empresa que más nos ha solicitado las modificaciones en los tableros. 

Se siguen presentando los NULL en los tableros de CO2 y no se encuentran los datos actualizados en ninguno de los tableros. Faltan octubre, noviembre y diciembre 2023 y enero 2024.

En el tablero de Ralenti es aun más grave ya que solo parecen datos de enero a julio de 2023 y solo dos vehiculos.

Con esta empresa es sumamente importante que podamos tener el archivo de trazabilidad de las estadisticas del preprocesamiento @HelmuthRaddatz

**Comment by HelmuthRaddatz** [comment]
Correcciones:
- Se agregaron los meses de octubre, noviembre y diciembre 2023, y enero 2024 para cada tablero.
- Se corrigió el error de "null" en el tablero de "EMISIONES CO2".
- Se pueden visualizar todos los vehículos y fechas en el tablero de "CONSUMO COMBUSTIBLE Y EMISIONES CO2 EN RALENTÍ".

**Favor revisar en: https://public.tableau.com/app/profile/reportes.pozuelo/vizzes.**

@Anamontesf

**Comment by Anamontesf** [comment]
Se revisaron los tablero y no se encontraron los meses mencionados de octubre, noviembre, diciembre 2023 y enero 2024 en el tablero de Emisiones de C02. 

![image](https://github.com/Anamontesf/GiroZero-GPS-/assets/90660279/fe737516-7bbc-46ea-9044-9cc536fb6b25)

Por otro lado en la revisión encontramos que los valores de consumo en dolares son bastante bajos segun lo reportado como base para la empresa y los demás indicadores tambien presentan unos valores demasiado bajos por lo cual solicitamos que se realice una verificación de estos calculos y cifras.

Aidiconalmente con esta empresa es sumamente importante que podamos tener el archivo de trazabilidad de las estadisticas del preprocesamiento @HelmuthRaddatz  ya que debemos socializar la trazabilidad completa.

**Comment by HelmuthRaddatz** [comment]
Dashboard actualizado con los meses indicados. El consumo en dólares será revisado, así como el archivo de trazabilidad que se menciona.
@Anamontesf

**Comment by camilafcubillos** [comment]
Por favor revisar el tablero de emisiones co2 cuando están todos los meses marcados aparecen 34 vehículos. Conforme la trazabilidad que se ha hecho con Nicaragua Pozuelo, se tiene los siguientes vehículos, 

2022 
oct 20 veh
nov 22 veh 
dic 22 veh

2023 ene 22 veh
feb 21 veh
marzo 24 veh 
abril 23 veh
mayo 23 veh 
junio 24 veh 
julio 21 veh 
agosto-septiembre (pendientes)
oct-nov-dic 21 veh 

2024
enero 21 veh

Así que hay que revisar el tablero, dado que los vehículos máximos han sido solo 24, lo pueden corroborar en la trazabilidad o fichas de entrada de Excel. @HelmuthRaddatz

**Comment by HelmuthRaddatz** [comment]
Estimada @camilafcubillos, la trazabilidad extraída por @AngeloValenzuelaP nos indica lo siguiente:

![image](https://github.com/user-attachments/assets/3bd20949-4c85-4f79-b464-3131ae4c59c9)

De este modo, los vehículos identificados son: 

1. M046-008
2. M046-015
3. M046-041
4. M101-321
5. M101-322
6. M101-324
7. M161-821
8. M161-822
9. M161-826
10. M163-639
11. M163-643
12. M012117
13. M046008
14. M046015
15. M046041
16. M046050
17. M101320
18. M101321
19. M101322
20. M101324
21. M161821
22. M161822
23. M161826
24. M163639
25. M163643
26. M302650
27. M306260
28. M339944
29. M339945
30. M339947
31. M339948
32. M346595
33. M346597
34. M365785

Siendo 34 vehículos en total.

**Comment by camilafcubillos** [comment]
Perfecto. mil gracias!
