### ISSUE TITLE
AMBIENTE Y SOLUCIONES SAS

### ISSUE THREAD

**Issue by camilafcubillos** [Anamontesf/GiroZero-GPS-#35]
Se requiere LINK o datos procesados de la empresa AMBIENTE Y SOLUCIONES SAS

Se dejan los archivos revisados en la dirección:

https://uniandes.sharepoint.com/:f:/r/sites/UKPACT-GiroZero-GiroZeroGPS/Documentos%20compartidos/GiroZero%20GPS/AMBIENTE%20Y%20SOLUCIONES%20SAS/2.%20DATOS%20REVISADOS/2.%20ENERO%20A%20JUNIO%20DEL%202O23?csf=1&web=1&e=KCGyNC 

La trazabilidad la encuentran en:
https://uniandes.sharepoint.com/:x:/r/sites/UKPACT-GiroZero-GiroZeroGPS/Documentos%20compartidos/GiroZero%20GPS/AMBIENTE%20Y%20SOLUCIONES%20SAS/2.%20DATOS%20REVISADOS/1.%20INFORMACI%C3%93N%20PLACAS/AMBIENTE%20Y%20SOLUCIONES%20SAS_%20TRAZABILIDAD.xlsx?d=w8066a06325cb4cbaab52afdf75a798bc&csf=1&web=1&e=dqSFyu

Se requiere el tablero y fichas de salida para el día 20 de AGOSTO del 2023, con el fin de reportar a externos.

La estructura de las carpetas es de este modo:
NOMBRE DE LA EMPRESA
1. DATOS BRUTOS
2. DATOS REVISADOS
1. INFORMACIÓN PLACAS
NOMBRE DE LA EMPRESA_TRAZABILIDAD
2. ENERO A JUNIO DEL 2023
3. DATOS PROCESADOS

**Comment by Eduardo-Encina** [comment]
Hola, el proceso de actualización de datos de la empresa AMBIENTE Y SOLUCIONES SAS se encuentra finalizado:
- Link dashboard's: https://public.tableau.com/app/profile/reportes.ambiente.soluciones

**Comment by camilafcubillos** [comment]
Los tableros de DATALOG, CONFIPETROL, AMBIENTES Y SOLUCIONES tienen la misma distancia recorrida en los tableros de emisiones de CO2, se puede revisar ese dato, ya que, entre empresas varia el número de vehiculos y operacion. @Eduardo-Encina

El dato de distancia recorrida es de 268.264,2 km, se tiene el dato de consumo y galones iguales en los tres tableros, por favor verificar valores.

**Comment by Anamontesf** [comment]
El tablero de Emisiones CO2 sigue presentando NULL en el filtro de seleccion de vehiculos y tambien en el de mes.

Adicionalmente no se encuentran las estadisticas de preprocesamiento en teams @HelmuthRaddatz

**Comment by HelmuthRaddatz** [comment]
Estimada @Anamontesf, ya se encuentra actualizado el tablero "Emisiones CO2". En esta instancia no se presentan vehículos con NULL.
Sin embargo, quiero destacar que el procesamiento de datos ha dejado algunos registros que se encontraban **fuera de la zona de estudio**, los cuales correspondían a los NULL.

**Comment by HelmuthRaddatz** [comment]
Estimadas, el detalle de procesamiento de los vehículos emitido por @AngeloValenzuelaP es el siguiente:
![image](https://github.com/user-attachments/assets/b9a54386-91fb-45cb-85ef-c18e6d3ddc48)

Siendo los vehículos visualizados:
1. EQO966
2. KNZ815
3. KNZ817
4. TTX627
5. WFH141
6. WFI010
