### ISSUE TITLE
DATALOG

### ISSUE THREAD

**Issue by camilafcubillos** [Anamontesf/GiroZero-GPS-#36]
Se encuentra la información organizada y filtrada con el respectivo archivo de reporte de resultados:

https://uniandes.sharepoint.com/:f:/r/sites/UKPACT-GiroZero-GiroZeroGPS/Documentos%20compartidos/GiroZero%20GPS/DATALOG/2.%20DATOS%20REVISADOS?csf=1&web=1&e=o1ZD4O

La estructura de las carpetas se encuentra de este modo:
NOMBRE DE LA EMPRESA (DATALOG)

1.DATOS BRUTOS
2.DATOS REVISADOS (Contiene nuestro excel con la revision realizada y los archivos debidamente filtrados)
3.DATOS PROCESADOS

Se requiere el tablero y fichas de salida para el día 20 de AGOSTO del 2023, con el fin revisar los output, validar el funcionamiento de los protocolos y reportar resultados a externos.

**Comment by Anamontesf** [comment]
Datos listos para procesar @Eduardo-Encina

**Comment by Eduardo-Encina** [comment]
Hola, el proceso de actualización de datos de la empresa DATALOG se encuentra finalizado:

**Link dashboard's:** https://public.tableau.com/app/profile/reportes.datalog

**Comment by camilafcubillos** [comment]
Los tableros de DATALOG, CONFIPETROL, AMBIENTES Y SOLUCIONES tienen la misma distancia recorrida en los tableros de emisiones de CO2, se puede revisar ese dato, ya que, entre empresas varia el número de vehiculos y operacion. @Eduardo-Encina 

El dato de distancia recorrida es de 268.264,2 km, se tiene el dato de consumo y galones iguales en los tres tableros, por favor verificar valores.

**Comment by camilafcubillos** [comment]
Mismo tema con filtro NULL para revisar @Eduardo-Encina

**Comment by Anamontesf** [comment]
El tablero de CO2 aun tiene un NULL en el filtro de seleccion de vehiculo y en el filtro de Mes, adicionalmente no se encontro el archivo de estadisticas del preprocesamiento en teams @HelmuthRaddatz

**Comment by HelmuthRaddatz** [comment]
Se ha corregido el tablero. Puede ser visualizado en el siguiente enlace: https://public.tableau.com/app/profile/reportes.datalog/viz/EmisionesCO2_16942004883370/EMISIONESCO2?publish=yes.

La cantidad de registros procesados por @AngeloValenzuelaP siguen el siguiente detalle:
![image](https://github.com/user-attachments/assets/ac891df2-9c8f-4135-9102-029565be4aa2)

Los vehículos medidos son:
1. FZY449
2. GBM612
