### ISSUE TITLE
SEFARCOL

### ISSUE THREAD

**Issue by camilafcubillos** [Anamontesf/GiroZero-GPS-#37]
Se encuentra la información organizada y filtrada con el respectivo archivo de reporte de resultados:

https://uniandes.sharepoint.com/:f:/r/sites/UKPACT-GiroZero-GiroZeroGPS/Documentos%20compartidos/GiroZero%20GPS/SEFARCOL/2.%20DATOS%20REVISADOS?csf=1&web=1&e=MJG2BK

La estructura de las carpetas se encuentra de este modo:
NOMBRE DE LA EMPRESA (SEFARCOL)

1.DATOS BRUTOS
2.DATOS REVISADOS (Contiene nuestro excel con la revision realizada y los archivos debidamente filtrados)
3.DATOS PROCESADOS

Se requiere el tablero y fichas de salida para el día 28 de AGOSTO del 2023, con el fin revisar los output, validar el funcionamiento de los protocolos y reportar resultados a externos.

**Comment by Anamontesf** [comment]
Datos listos para procesar @Eduardo-Encina

**Comment by Eduardo-Encina** [comment]
Hola, el proceso de actualización de datos de la empresa **SEFARCOL** se encuentra finalizado:

- Link dashboard's: https://public.tableau.com/app/profile/reportes.sefarcol/vizzes
@camilafcubillos @Anamontesf

**Comment by camilafcubillos** [comment]
Sefarcol tiene las placas de confipetrol, en el tablero no estan las placas de la empresa sino de otra, por favor revisar y corregir. @Eduardo-Encina

**Comment by camilafcubillos** [comment]
Tablero corregido y actualizado

**Comment by Anamontesf** [comment]
Los tableros estan OK, pero no se encontro el archivo de estadisticas del preprocesamiento en teams @HelmuthRaddatz

**Comment by HelmuthRaddatz** [comment]
Estimada @Anamontesf, la estadística enviada por @AngeloValenzuelaP es de la siguiente estructura:
![image](https://github.com/user-attachments/assets/4cda92d3-8389-4b4f-93ae-e2964cff71c9)

Los vehículos procesados fueron:
1. ERL434
2. WLR090
