### ISSUE TITLE
REPREMUNDO

### ISSUE THREAD

**Issue by camilafcubillos** [Anamontesf/GiroZero-GPS-#38]
Se encuentra la información organizada y filtrada con el respectivo archivo de reporte de resultados:

https://uniandes.sharepoint.com/:f:/r/sites/UKPACT-GiroZero-GiroZeroGPS/Documentos%20compartidos/GiroZero%20GPS/REPREMUNDO/2.%20DATOS%20REVISADOS?csf=1&web=1&e=VKoqax

La estructura de las carpetas se encuentra de este modo:
NOMBRE DE LA EMPRESA (REPREMUNDO)

1.DATOS BRUTOS
2.DATOS REVISADOS (Contiene nuestro excel con la revision realizada y los archivos debidamente filtrados)
3.DATOS PROCESADOS

Se requiere el tablero y fichas de salida para el día 28 de AGOSTO del 2023, con el fin revisar los output, validar el funcionamiento de los protocolos y reportar resultados a externos.

**Comment by camilafcubillos** [comment]
Datos listos para procesar @Eduardo-Encina

**Comment by Eduardo-Encina** [comment]
Hola, el proceso de actualización de datos de la empresa **REPREMUNDO** se encuentra finalizado:

- Link dashboard's: https://public.tableau.com/app/profile/reportes.repremundo

**Comment by camilafcubillos** [comment]
Mismo situación con NULL, si se aplica quedan los mismos datos, necesario quitarlo 

@Eduardo-Encina

**Comment by Anamontesf** [comment]
El tablero de Emisiones CO2 sigue presentando NULL en el filtro de seleccion de vehiculos.

Adicionalmente no se encuentran las estadisticas de preprocesamiento en teams @HelmuthRaddatz

**Comment by HelmuthRaddatz** [comment]
Estimada @Anamontesf, se ha corregido este error y se puede visualizar en el enlace: https://public.tableau.com/app/profile/reportes.repremundo/viz/EmisionesCO2_16947237604840/EMISIONESCO2.

La estadística entregada por @AngeloValenzuelaP muestra el siguiente procesamiento de los datos:
![image](https://github.com/user-attachments/assets/f8f2a1ab-200c-4602-a327-d965d267be95)

Siendo los vehículos del siguiente listado:
1. EQP877
2. EQP878
3. EXX794
4. JOV882
5. JOV883
6. LCO676
7. LCO678
8. SML881
9. SMN523
10. SMO903
11. SPT733
12. TDL525
13. TDL526
14. TZR888
15. UFW095
16. UFX817
17. UPQ946
18. WCY056
19. WCY057
20. WFV228
21. WFV341
22. WFW051
23. WLL026
24. WLL027
25. WLM647
26. WLM662
27. WNX269
