### ISSUE TITLE
SAVILLA SAS

### ISSUE THREAD

**Issue by camilafcubillos** [Anamontesf/GiroZero-GPS-#39]
Se encuentra la información organizada y filtrada con el respectivo archivo de reporte de resultados:

https://uniandes.sharepoint.com/:f:/r/sites/UKPACT-GiroZero-GiroZeroGPS/Documentos%20compartidos/GiroZero%20GPS/SAVILLA/2.%20DATOS%20REVISADOS?csf=1&web=1&e=Lhba74

La estructura de las carpetas se encuentra de este modo:
NOMBRE DE LA EMPRESA (SAVILLA SAS)

1.DATOS BRUTOS
2.DATOS REVISADOS (Contiene nuestro excel con la revision realizada y los archivos debidamente filtrados)
3.DATOS PROCESADOS

Se requiere el tablero y fichas de salida para el día 28 de AGOSTO del 2023, con el fin revisar los output, validar el funcionamiento de los protocolos y reportar resultados a externos.

**Comment by camilafcubillos** [comment]
Todo quedo revisado para proceder con el procesamiento de datos @Eduardo-Encina

**Comment by Eduardo-Encina** [comment]
Por favor, les agradecería poder enviarme logo de la empresa.
@Anamontesf @camilafcubillos

**Comment by Eduardo-Encina** [comment]
Hola, el proceso de actualización de datos de la empresa SAVILLAS SAS se encuentra finalizado:

- **Link dashboard's:** https://public.tableau.com/app/profile/reportes.savilla/vizzes

@camilafcubillos @Anamontesf

**Comment by Anamontesf** [comment]
Los tableros se encuentran OK. 

Solo falta el archivo de estadisticas de preprocesamiento en teams @HelmuthRaddatz

**Comment by HelmuthRaddatz** [comment]
Estimada @Anamontesf, el procesamiento de esta empresa sigue la siguiente estadística extraída por @AngeloValenzuelaP:
![image](https://github.com/user-attachments/assets/a05a5665-d5c3-4dd0-94f7-8e7fd6de18e4)

Los vehículos son:

1. 155NAN
2. AEI848
3. AKI357
4. AOU32
5. BGP295
6. BJF020
7. BSF845
8. BSJ654
9. DGE43E
10. EQP170
11. EQQ460
12. EQW784
13. EQY844
14. EQY996
15. EQZ110
16. ERK215
17. ERK626
18. ERL590
19. Esc A Bueno SRA87B
20. Esc A Cervantes DID79C
21. Esc A Perez QGP53E
22. Esc E Arevalo IMM87F
23. Esc E Cardozo VCQ38D
24. Esc E Mejia PYJ35C
25. Esc Eduin IMM87F
26. Esc F Grajales RXX54D
27. Esc F Guevara KJG92G
28. Esc F Prada AUM80E
29. Esc Ferney KJG92G
30. Esc H Londoño SSD15E
31. Esc I Montoya URK14E
32. Esc J Agredo JET51A
33. Esc J Bravo AHE80E
34. Esc J Gutierrez YRF27E
35. Esc J Muñoz OEN08E
36. Esc J Ospina RSZ26F
37. Esc J Tirado NLS29E
38. Esc J Zipa MVE23E
39. Esc Jaime Jimenez MSV18D
40. Esc Julio RSZ26F
41. Esc LL Billin LQC20G
42. Esc M Clavijo LCH55G
43. Esc Milton QZW46G
44. Esc O Valencia NDC83D
45. Esc R Lugo SEO95E
46. ESC S CLAVIJO OGX89F
47. Esc Sandoval WLJ24E
48. ESC SAUL OGX89F
49. Esc V Garces NLI79E
50. ESCO09
51. ESP002
52. ESQ462
53. ESQ936
54. EST590
55. ESZ338
56. ESZ531
57. ESZ647
58. ESZ663
59. EXU598
60. EXU679
61. EXU679_C
62. EXU680
63. EXU680_C
64. EXU681
65. EXU681_C
66. EXU682
67. EXU682_C
68. EXU683
69. EXU684
70. EXU684_C
71. EXU685
72. EXU685_C
73. EXU690
74. EXU690_C
75. EXU691
76. EXU691_C
77. EXU692
78. EXU692_C
79. EXZ179
80. EYX242
81. FST661
82. FST794
83. FSU233
84. FSU287
85. FSV752
86. FSW165
87. FWM133
88. FZY704
89. GDY443
90. GFP857
91. GFP910
92. GFP942
93. GIM087
94. GNK503
95. GQW410
96. GTX988
97. GTZ148
98. GUR128
99. GUR764
100. GZZ563
101. GZZ814
102. IBY129
103. IBY682
104. IMR067
105. IYM177
106. IYM187
107. IYM192
108. IYM194
109. IYM197
110. IYM198
111. JDK017
112. JKU047
113. JKU843
114. JKU906
115. JKV244
116. JKV589
117. JKV614
118. JKV615
119. JKW064
120. JOV750
121. JOW696
122. JPP296
123. JPP334
124. JTQ119
125. JTX705
126. JTY607
127. JTZ004
128. JTZ839
129. JUY547
130. JUY548
131. JUY728
132. JUY729
133. JUY924
134. JUY925
135. JUY926
136. JUY927
137. JUY928
138. JUY988
139. JUY989
140. JVL326
141. JVM033
142. JXU87F
143. JYW830
144. KFR821
145. KJS93E
146. KNL006
147. KOK800
148. KOK801
149. KOK802
150. KOK803
151. KOK804
152. KOK805
153. KOK806
154. KOK807
155. KOK808
156. KOK809
157. KOK914
158. KOK915
159. KOK916
160. KOK918
161. KOK919
162. KOK920
163. KOK999
164. KOL223
165. KOL231
166. KOL232
167. KOL233
168. KOL234
169. KPO661
170. KPO679
171. KPP028
172. KPP034
173. KSK562
174. KSQ153
175. KSR092
176. KUK354
177. KUK705
178. KUK812
179. KUL254
180. KUN003
181. KUN030
182. KUN701
183. KUS322
184. KZL126
185. LAT985
186. LAT993
187. LFX332
188. LJS763
189. LJS764
190. LJT381
191. LKK423
192. LLO997
193. LSX439
194. LUF72E
195. LUL211
196. LUL351
197. LUL352
198. LUL353
199. LUL354
200. LUL355
201. LUL356
202. LUL357
203. LUL358
204. LUL359
205. LUL360
206. LUL361
207. LUL362
208. LUL363
209. LUL364
210. LUL365
211. LUL366
212. LUL367
213. LUL368
214. LUL377
215. LUL560
216. LUL561
217. LUL562
218. LUL563
219. LUL564
220. LUL565
221. LUL566
222. LUL567
223. LUL568
224. LZL903
225. LZL904
226. LZL905
227. LZL906
228. LZL907
229. LZR523
230. MBL730
231. MBL733
232. MBL739
233. MBQL04
234. MCGN02
235. MIB001
236. MMD004
237. MMD005
238. MMD006
239. MMD007
240. MMD008
241. MMD009
242. MMD011
243. MMD012
244. MMD013
245. MMD014
246. MMD015
247. MMD016
248. MMD017
249. MMD018
250. MMD019
251. MMD020
252. MMF50E
253. MPR071
254. OJF457
255. QYE11C
256. R03585
257. R12385
258. R12400
259. R13315
260. R14789
261. R15112
262. R24265
263. R30355
264. R30356
265. R30372
266. R30677
267. R31482
268. R33193
269. R34929
270. R35473
271. R35474
272. R35475
273. R37600
274. R37601
275. R40335
276. R40336
277. R42110
278. R42112
279. R51064
280. R51066
281. R51067
282. R51068
283. R51069
284. R51605
285. R51606
286. R51607
287. R54432
288. R54433
289. R54434
290. R54435
291. R68530
292. R68531
293. R68532
294. R72168
295. R72169
296. R72170
297. R72171
298. R76484
299. RAX877
300. RHP052
301. RHQ902
302. RHQ903
303. RZG784
304. RZR557
305. S21166
306. S21167
307. S21168
308. S21169
309. S46759
310. S46760
311. S46762
312. S52336
313. S55173
314. S55441
315. S55442
316. S55443
317. S55444
318. S55445
319. S55446
320. S55447
321. S55448
322. S55450
323. S55451
324. S55452
325. S55453
326. S57444
327. S57457
328. S59943
329. S59944
330. S59945
331. S66756
332. S66757
333. S66758
334. S66760
335. S69811
336. S69813
337. S69814
338. S76375
339. S76376
340. S76443
341. S76444
342. S76445
343. S76446
344. S76447
345. S76448
346. S76449
347. S76464
348. S76465
349. S76466
350. S76467
351. S76468
352. S76469
353. S76470
354. S599441
355. SBL498
356. SELLO1
357. SELLO2
358. SELLO3
359. SELLO4
360. SELLO5
361. SELLO6
362. SIB696
363. SIL685
364. SIL994
365. SIM570
366. SKK655
367. SKM494
368. SKN054
369. SKN543
370. SKX214
371. SKY843
372. SKZ506
373. SLG688
374. SLG716
375. SLI317
376. SLI318
377. SLI319
378. SLI320
379. SLI321
380. SLI322
381. SLJ476
382. SMM619
383. SMO641
384. SMT571
385. SND983
386. SNM770
387. SNP400
388. SNP439
389. SNP618
390. SNR056
391. SNR158
392. SNR159
393. SNU001
394. SNX019
395. SNX392
396. SNX478
397. SNX952
398. SOI129
399. SOI133
400. SOI139
401. SOZ429
402. SPK201
403. SPO562
404. SPO796
405. SPQ272
406. SPQ312
407. SPS021
408. SPS914
409. SPV788
410. SQI748
411. SQJ722
412. SQL402
413. SQW037
414. SRE467
415. SRF231
416. SRF232
417. SRJ626
418. SRL686
419. SRN299
420. SRN923
421. SRO011
422. SRP540
423. SST378
424. SSY114
425. SSZ201
426. STA729
427. STS375
428. STS531
429. STS532
430. STS611
431. STS812
432. STV082
433. STW363
434. STY453
435. SUA704
436. SUD503
437. SVB351
438. SWK041
439. SWK421
440. SWK932
441. SWM372
442. SWN989
443. SWO300
444. SWQ109
445. SWQ325
446. SWQ325_C
447. SWQ326
448. SWQ326_C
449. SWX117
450. SXC740
451. SXJ700
452. SXN901
453. SXX300
454. SXZ084
455. SYQ599
456. SYS306
457. SYS528
458. SYT761
459. SZK245
460. SZK344
461. SZL251
462. SZL706
463. SZL883
464. SZM037
465. SZM309
466. SZM491
467. SZM582
468. SZM700
469. SZM703
470. SZP512
471. SZQ368
472. SZU148
473. SZW575
474. SZW593
475. SZW593_C
476. SZW594
477. SZW594_C
478. SZW597
479. SZW597_C
480. SZW598
481. SZW598_C
482. SZW601
483. SZW601_C
484. SZW605
485. SZW605_C
486. SZW606
487. SZW606_C
488. SZW608
489. SZW609
490. SZW609_C
491. SZW611
492. SZX021
493. SZX274
494. SZX329
495. SZY580
496. SZY622
497. SZY624
498. SZY624_C
499. SZZ267
500. TAL200
501. TAL200_C
502. TAL201
503. TAL201_C
504. TAL204
505. TAL204_C
506. TAL206
507. TAL206_C
508. TAL207
509. TAL208
510. TAL208_C
511. TAL209
512. TAL209_C
513. TAL435
514. TAM212
515. TAM212_C
516. TAW077
517. TAW653
518. TBY204
519. TBZ736
520. TDK877
521. TDL090
522. TDL516
523. TDL517
524. TDL762
525. TDS221
526. TDU877
527. TEK420
528. TEW090
529. TFP290
530. TFU212
531. TFU713
532. TFU939
533. TFU940
534. TFU941
535. TGK178
536. TGK179
537. TGK180
538. TGK537
539. TGK640
540. TGL149
541. TGL149_C
542. TGL150
543. TGL150_C
544. TGL154
545. TGL154_C
546. TGV501
547. TGY448
548. THR313
549. THS402
550. THX629
551. THY153
552. THY397
553. THY876
554. TJW385
555. TJW846
556. TJX633
557. TJX776
558. TKF415
559. TLM016
560. TLM016_C
561. TLM017
562. TLM017_C
563. TLM110
564. TLN570
565. TLO216
566. TLX648
567. TLZ417
568. TMZ208
569. TND642
570. TOQ166
571. TRAYLER_21
572. TRAYLER_30
573. TRK995
574. TRM433
575. TSM044
576. TSW100
577. TSX050
578. TTR294
579. TTS581
580. TTS941
581. TTT199
582. TTT252
583. TTT387
584. TTY796
585. TTY797
586. TTY798
587. TTY799
588. TTZ706
589. TTZ828
590. TTZ954
591. TUK357
592. TVA236
593. TVB905
594. TVC132
595. TVC164
596. TZL546
597. TZL846
598. TZO646
599. TZQ016
600. TZQ723
601. TZT076
602. TZT395
603. UAM763
604. UFR869
605. UFR870
606. UFT654
607. UFT657
608. UFT659
609. UFU445
610. UFW131
611. UPN230
612. UPN758
613. UPO057
614. UPO260
615. UPO766
616. UPP063
617. UPP591
618. UPP890
619. UPP900
620. UPQ08F
621. UPQ968
622. UPQ969
623. UPQ970
624. UPR114
625. UPS302
626. UPT318
627. UPT335
628. UPT509
629. UQE551
630. UQF413
631. USA541
632. USA861
633. USC923
634. USE223
635. UYT502
636. UZC058
637. VCS930
638. VCV653
639. VEC196
640. VEC358
641. VED265
642. VEH004
643. VEW749
644. VKK352
645. VMU789
646. VOJ896
647. WBG747
648. WCP324
649. WCP357
650. WCQ008
651. WCQ309
652. WCQ558
653. WCR918
654. WCS190
655. WCT016
656. WCT791
657. WCV721
658. WCW600
659. WCZ007
660. WCZ281
661. WCZ340
662. WCZ672
663. WCZ771
664. WDE623
665. WDL582
666. WEL968
667. WEM167
668. WEQ953
669. WFC188
670. WFD504
671. WFG822
672. WFG855
673. WFH358
674. WFH871
675. WFH871_C
676. WFH872
677. WFH872_C
678. WFH931
679. WFH931_C
680. WFH992
681. WFH992_C
682. wfi016
683. WFI020
684. WFI020_C
685. WFI036
686. WFI036_C
687. WFI037
688. WFI037_C
689. WFI038
690. WFI038_C
691. WFI039
692. WFI039_C
693. WFI040
694. WFI040_C
695. WFI041
696. WFI041_C
697. WFI043
698. WFI043_C
699. WFI044
700. WFI044_C
701. WFI045
702. WFI045_C
703. WFI421
704. WFI421_C
705. WFR175
706. WFR665
707. WFR668
708. WFR674
709. WFR684
710. WFR693
711. WFR697
712. WFV175
713. WFV412
714. WFV413
715. WFV801
716. WFW075
717. WFW076
718. WFW174
719. WGB697
720. WGO599
721. WGQ165
722. WGU350
723. WGU472
724. WGU554
725. WGU763
726. WGW003
727. WGW235
728. WGW656
729. WGW957
730. WGX017
731. WGX228
732. WGX288
733. WGY859
734. WGZ858
735. WGZ959
736. WHO525
737. WHU830
738. WHU872
739. WHW301
740. WHW565
741. WLK239
742. WLK393
743. WLL561
744. WLL828
745. WLN219
746. WLQ241
747. WLQ690
748. WLQ968
749. WLR460
750. WLR748
751. WLS510
752. WLS620
753. WLS750
754. WLU500
755. WLW461
756. WLX173
757. WLX511
758. WLX761
759. WLY923
760. WMO002
761. WNK542
762. WNM251
763. WNM261
764. WNO328
765. WNO495
766. WNP870
767. WNP870_C
768. WNP871
769. WNP871_C
770. WNP872
771. WNP872_C
772. WNP873
773. WNP873_C
774. WNP874
775. WNP874_C
776. WNP875
777. WNP875_C
778. WNP876
779. WNP876_C
780. WNP877
781. WNP877_C
782. WNP879
783. WNP879_C
784. WNP880
785. WNP880_C
786. WNP881
787. WNP881_C
788. WNP882
789. WNP882_C
790. WNP883
791. WNP883_C
792. WNP884
793. WNP884_C
794. WNP885
795. WNP886
796. WNP887
797. WNP888
798. WNP888_C
799. WNP889
800. WNP889_C
801. WNP890
802. WNP890_C
803. WNP891
804. WNP891_C
805. WNP892
806. WNP892_C
807. WNP893
808. WNP893_C
809. WNP894
810. WNP894_C
811. WNP895
812. WNP895_C
813. WNP896
814. WNP896_C
815. WNP897
816. WNP897_C
817. WNP898
818. WNP898_C
819. WNP899
820. WNP899_C
821. WNP900
822. WNP900_C
823. WNP901
824. WNP901_C
825. WNP902
826. WNP902_C
827. WNP903
828. WNP903_C
829. WNP904
830. WNP904_C
831. WNP905
832. WNP905_C
833. WNP906
834. WNP906_C
835. WNP907
836. WNP907_C
837. WNP908
838. WNP908_C
839. WNP909
840. WNP909_C
841. WNP910
842. WNP910_C
843. WNP912
844. WNP912_C
845. WNP913
846. WNP913_C
847. WNP914
848. WNP915
849. WNP915_C
850. WNP916
851. WNP916_C
852. WNP917
853. WNP917_C
854. WNQ089
855. WNQ090
856. WNQ091
857. WNQ092
858. WNQ093
859. WNQ094
860. WNQ095
861. WNQ096
862. WNQ097
863. WNQ098
864. WNQ099
865. WNQ100
866. WNX854
867. WNZ742
868. WOL104
869. WOO816
870. WOS919
871. WOU712
872. WOW339
873. WOX295
874. WPR883
875. WPS129
876. WPU009
877. WPW143
878. WPW376
879. WTL434
880. WTL858
881. XJA067
882. XJA068
883. XJA069
884. XJA379
885. XMA866
886. XMB399
887. XMD975
888. XVN455
889. YAQ757
890. YAR087
891. YAR088
892. ZAP945
893. ZIG069
894. ZNL383
895. ZNM920
896. ZNN498

**Comment by Anamontesf** [comment]
Hola @HelmuthRaddatz segun la revision realizada se encontro lo siguiente:

![image](https://github.com/user-attachments/assets/86328cca-0e22-440b-8f10-3421107193f0)

Como se observa en la imagen nosotros solo tenemos conocimiento de los 7 vehiculos con los 3 meses que estan reportados en los tableros y esos estan todos ok, no entendemos de donde viene el listado de los 896 vehiculos que adjuntas, no corresponden a nuestros archivos.

Por favor indicar de donde sacan esas información, ya que no concuerda ni con los tableros entregados (que para el caso estan bien y por ese lado si podemos cerrar el issue) pero no entendemos de donde sacan esta información de otros vehiculos que ni siquiera ponen en los tableros entregados pero si en el archivo de entregables como adjunto en la siguiente imagen. 

![image](https://github.com/user-attachments/assets/2acbc3a1-1c25-45cc-9ef6-f395f3a7bcde)

**Comment by Anamontesf** [comment]
Hola @HelmuthRaddatz,

Encontre que esta información reportada de estos 896 vehiculos en realidad corresponde a SOLISTICA

![image](https://github.com/user-attachments/assets/8db17501-3300-478f-ae8f-47f543341b16)

Como se adjunta en la imagen estan confundiendo las empresas y los archivos de trazabilidad.
