### ISSUE TITLE
FEPCO ZONA FRANCA

### ISSUE THREAD

**Issue by camilafcubillos** [Anamontesf/GiroZero-GPS-#40]
Se encuentra la información organizada y filtrada con el respectivo archivo de reporte de resultados:

https://uniandes.sharepoint.com/:f:/r/sites/UKPACT-GiroZero-GiroZeroGPS/Documentos%20compartidos/GiroZero%20GPS/FEPCO%20ZONA%20FRANCA/2.%20DATOS%20REVISADOS?csf=1&web=1&e=TYa7g7

La estructura de las carpetas se encuentra de este modo:
NOMBRE DE LA EMPRESA (FEPCO ZONA FRANCA)

1.DATOS BRUTOS
2.DATOS REVISADOS (Contiene nuestro excel con la revision realizada y los archivos debidamente filtrados)
3.DATOS PROCESADOS

Se requiere el tablero y fichas de salida para el día 28 de AGOSTO del 2023, con el fin revisar los output, validar el funcionamiento de los protocolos y reportar resultados a externos.

**Comment by Eduardo-Encina** [comment]
Hola, el proceso de actualización de datos de la empresa FEPCO se encuentra finalizado:

**Link dashboard's:** https://public.tableau.com/app/profile/reportes.fepco

**Comment by Anamontesf** [comment]
En la revision se encontro que se encuentra aun un filtro de NULL en el tablero de emisiones C02, por favor revisar. 

Adicionalmente no se encontro el archivo de estadisticas de preprocesamiento en la carpeta de teams @HelmuthRaddatz

**Comment by HelmuthRaddatz** [comment]
Tablero corregido con errores de patentes con NULL. Mayo, junio y julio del 2023 con 3 vehículos.

Favor revisar en: https://public.tableau.com/app/profile/reportes.fepco/viz/EmisionesCO2_16942077649350/EMISIONESCO2?publish=yes

**Comment by HelmuthRaddatz** [comment]
El procesamiento de estos datos obtenido por @AngeloValenzuelaP sigue el siguiente resumen:
![image](https://github.com/user-attachments/assets/672c3b18-b1f2-4f69-8805-9bfccd54ea97)

Los vehículos son:
1. FST980
2. SOP122
3. SPT553
