### ISSUE TITLE
INSTALACIONES HIDRAULICAS

### ISSUE THREAD

**Issue by camilafcubillos** [Anamontesf/GiroZero-GPS-#41]
Se encuentra la información organizada y filtrada con el respectivo archivo de reporte de resultados:

https://uniandes.sharepoint.com/:f:/r/sites/UKPACT-GiroZero-GiroZeroGPS/Documentos%20compartidos/GiroZero%20GPS/INSTALACIONES%20HIDRAULICAS%20Y%20SANITARIAS/2.%20DATOS%20REVISADOS?csf=1&web=1&e=u5YULS

La estructura de las carpetas se encuentra de este modo:
NOMBRE DE LA EMPRESA (INSTALACIONES HIDRAULICAS)

1.DATOS BRUTOS
2.DATOS REVISADOS (Contiene nuestro excel con la revision realizada y los archivos debidamente filtrados)
3.DATOS PROCESADOS

Se requiere el tablero y fichas de salida para el día 28 de AGOSTO del 2023, con el fin revisar los output, validar el funcionamiento de los protocolos y reportar resultados a externos.

**Comment by Anamontesf** [comment]
Datos listos para procesar @Eduardo-Encina

**Comment by Eduardo-Encina** [comment]
Hola, el proceso de actualización de datos de la empresa **INSTALACIONES HIDRAULICAS** se encuentra finalizado:

- **Link dashboard's:** https://public.tableau.com/app/profile/reportes.instalaciones.hidraulicas.y.sanitarias/vizzes

@camilafcubillos @Anamontesf

**Comment by camilafcubillos** [comment]
Esta empresa no tiene las placas que son esta empresa tiene las placas de FEPCO, las placas de instalaciones son otras, por favor revisar y corregir

**Comment by camilafcubillos** [comment]
Tablero corregido y actualizado

**Comment by Anamontesf** [comment]
Se revisaron los tableros y se encontro una inconsistencia en lo que respecta al numero de meses, los archivos como tal solo contienen datos de mayo, junio y julio. En el tablero de emisiones Co2 se observa en el filtro de fecha el mes de MARZO y al filtrar aparece un vehiculo asociado, por favor revisar.

Adicionalmente no se encuentra el archivo de estadisticas del preprocesamiento en teams @HelmuthRaddatz

**Comment by HelmuthRaddatz** [comment]
Este tablero fue cerrado y aprobado en noviembre del año pasado. No se han hecho cambios desde entonces, por lo que esta situación debió ser explicada por Eduardo previamente. 

Al revisar el dashboard efectivamente aparece la situación que comenta Ana, sin embargo, no puedo modificar este tablero hasta que sea visado y aprobado por Eduardo y Julio.
