### ISSUE TITLE
CONFIPETROL

### ISSUE THREAD

**Issue by camilafcubillos** [Anamontesf/GiroZero-GPS-#42]
Se encuentra la información organizada y filtrada con el respectivo archivo de reporte de resultados:

https://uniandes.sharepoint.com/:f:/r/sites/UKPACT-GiroZero-GiroZeroGPS/Documentos%20compartidos/GiroZero%20GPS/CONFIPETROL/2.%20DATOS%20REVISADOS?csf=1&web=1&e=U4G9pb

La estructura de las carpetas se encuentra de este modo:
NOMBRE DE LA EMPRESA (CONFIPETROL)

1.DATOS BRUTOS
2.DATOS REVISADOS (Contiene nuestro excel con la revision realizada y los archivos debidamente filtrados)
3.DATOS PROCESADOS

Se requiere el tablero y fichas de salida para el día 28 de AGOSTO del 2023, con el fin revisar los output, validar el funcionamiento de los protocolos y reportar resultados a externos.

**Comment by Anamontesf** [comment]
Datos listos para procesar @Eduardo-Encina

**Comment by Anamontesf** [comment]
Datos listo para procesar. @Eduardo-Encina

**Comment by Anamontesf** [comment]
Datos listos para procesar @Eduardo-Encina.

**Comment by camilafcubillos** [comment]
Los tableros de DATALOG, CONFIPETROL, AMBIENTES Y SOLUCIONES tienen la misma distancia recorrida en los tableros de emisiones de CO2, se puede revisar ese dato, ya que, entre empresas varia el número de vehiculos y operacion. @Eduardo-Encina 

El dato de distancia recorrida es de 268.264,2 km, se tiene el dato de consumo y galones iguales en los tres tableros, por favor verificar valores.

**Comment by camilafcubillos** [comment]
Se evidencia el mismo problema con el tema del NULL, dado que las empresas datalog, confipetrol, ambientes y soluciones, como repremundo quedan con los mismos datos, revisar ese filtro para quitarlo y que quede meramente el tema de confipetrol.

POR OTRO LADO, FALTAN LOS MESES MAYO Y JUNIO, solo esta el mes de JULIO, faltantes mayo y junio para esta empresa. @Eduardo-Encina

**Comment by Eduardo-Encina** [comment]
Correjido Empresa **Confipetrol**

**Comment by Anamontesf** [comment]
En la revision se encontro que se arreglaron los problemas de los valores iguales, ya aparecen los 3 meses y se arreglo el filtro con el NULL. 

Lo unico pendiente es el archivo de estadisticas del preprocesamiento en teams @HelmuthRaddatz

**Comment by HelmuthRaddatz** [comment]
Estimada @Anamontesf, la estadística obtenida por @AngeloValenzuelaP indica el siguiente resumen:
![image](https://github.com/user-attachments/assets/5f3b3d3a-626c-48e9-9281-ec555c1bb437)

Los vehículos son:

1. DSN346
2. DUL095
3. FVR699
4. FVR725
5. FVR726
6. GPZ296
7. GQS147
8. GSN441
9. GSO506
10. IRM721
11. IRM741
12. IRM760
13. IRM761

**Comment by Anamontesf** [comment]
Hola @HelmuthRaddatz en la revision se encontraron incosistencias en el tablero de Ralenti.

![image](https://github.com/user-attachments/assets/de4c6425-4a78-4309-8c3d-2a9030ec5f3e)

Como se observa en la imagen solamente 2 vehiculos de los 13 aparecen con detecciones, pero en la imagen que ustedes nos entregan en el comentario anterior de datos de salida procesados se indica que deberian aparecer 13 vehiculos.

Por otro lado tambien como se muestra en la imagen de datos de salida procesados solo son 3 meses y como puedes observar en la imagen de ralenti salen 7 lo cual no corresponde.

Por favor revisar estos detalles de ese tablero, los demás estan ok.
