### ISSUE TITLE
HDL-COLSUBSIDIO

### ISSUE THREAD

**Issue by camilafcubillos** [Anamontesf/GiroZero-GPS-#43]
Se encuentra la información organizada y filtrada con el respectivo archivo de reporte de resultados:

https://uniandes.sharepoint.com/:f:/r/sites/UKPACT-GiroZero-GiroZeroGPS/Documentos%20compartidos/GiroZero%20GPS/HDL%20-%20Colsubsidio/2.%20DATOS%20REVISADOS?csf=1&web=1&e=ppQPAu

La estructura de las carpetas se encuentra de este modo:
NOMBRE DE LA EMPRESA (HDL COLSUBSIDIO)

1.DATOS BRUTOS
2.DATOS REVISADOS (Contiene nuestro excel con la revision realizada y los archivos debidamente filtrados)
3.DATOS PROCESADOS

Se requiere el tablero y fichas de salida para el día 7 de SEPTIEMBE del 2023, con el fin revisar los output, validar el funcionamiento de los protocolos y reportar resultados a externos.

**Comment by HelmuthRaddatz** [comment]
Los datos se encuentran procesados y publicados. Se pueden visualizar en: https://public.tableau.com/app/profile/reportes.hdl.colsubsidio/vizzes

**Comment by Anamontesf** [comment]
En la revisión de los tableros, no se encuentra el tablero de emisiones de Co2, adicionalmente no se encuentra el archivo de estadisticas del procesamiento en teams @HelmuthRaddatz.

**Comment by HelmuthRaddatz** [comment]
Ya se encuentra disponible el tablero de EMISIONES CO2 para 20 vehículos procesados. 

Favor revisar en: https://public.tableau.com/app/profile/reportes.hdl.colsubsidio/vizzes

@Anamontesf @camilafcubillos @AngeloValenzuelaP

**Comment by Anamontesf** [comment]
Se reviso y se encontro que estan completos los tableros.

@HelmuthRaddatz  Unicamente quedaria faltando el archivo de trazabilidad de estadisticas del procesamiento.

**Comment by HelmuthRaddatz** [comment]
Estimada @Anamontesf, la estadística del procesamiento obtenido por @AngeloValenzuelaP sigue el siguiente resumen:
![image](https://github.com/user-attachments/assets/23de1f11-9367-4880-a1e0-a2812df6d024)

Los vehículos son:
1. BDG740
2. EQQ477
3. EQQ772
4. FSU666
5. GET408
6. JOV897
7. KSO641
8. SPX545
9. SVC271
10. SVD788
11. TDK509
12. THR275
13. TRM067
14. TZT351
15. UFX330
16. USA348
17. USC116
18. VFC224
19. WFI581
20. WFV061
21. WTL977

**Comment by Anamontesf** [comment]
Hola @HelmuthRaddatz  nos gustaria confirmar porque si en la imagen del comentario anteriore se tiene los 21 vehiculos en el tablero de detección en la revision actual solo aparecen 3. 

![image](https://github.com/user-attachments/assets/ac9e0315-c320-44ec-9e59-46e49ddb4ca3)

Por favor revisar y de ser el caso actualizar el archivo.

**Comment by Anamontesf** [comment]
En la revision se encontro que este mismo tablero con los mismos datos tambien lo tiene ALQUERIA y tampoco corresponde a lo reporta, por favor revisar esas inconsistencias.

![image](https://github.com/user-attachments/assets/b7aa779a-c08b-4455-ae69-c3ad1fb86874)
