### ISSUE TITLE
PAVIMENTOS DE COLOMBIA

### ISSUE THREAD

**Issue by camilafcubillos** [Anamontesf/GiroZero-GPS-#46]
SE REQUIERE LINK PARA EMPRESA PAVIMENTOS DE COLOMBIA:

DATOS REVISADOS EN: 

https://uniandes.sharepoint.com/:f:/r/sites/UKPACT-GiroZero-GiroZeroGPS/Documentos%20compartidos/GiroZero%20GPS/PAVIMENTOS%20COLOMBIA/2.%20DATOS%20REVISADOS?csf=1&web=1&e=oe6CcK

FECHA APROXIMADA DE ENTREGA 28 DE SEPTIEMBRE DEL 2023

**Comment by Eduardo-Encina** [comment]
Los datos de la empresa **PAVIMENTOS COLOMBIA** no es procesable, debido a que **no se encuentra en el formato acordado**. El archivo contiene sólo los inicios y fines de viaje, mas no la data gps desagregada.
@camilafcubillos @Anamontesf
