### ISSUE TITLE
HDL - Bimbo 

### ISSUE THREAD

**Issue by Anamontesf** [Anamontesf/GiroZero-GPS-#48]
Se encuentra la información organizada y filtrada con el respectivo archivo de reporte de resultados:

https://uniandes.sharepoint.com/:f:/r/sites/UKPACT-GiroZero-GiroZeroGPS/Documentos%20compartidos/GiroZero%20GPS/HDL%20-%20Bimbo?csf=1&web=1&e=rmCTwh

La estructura de las carpetas se encuentra de este modo:
NOMBRE DE LA EMPRESA (HDL- Bimbo)

1.DATOS BRUTOS
2.DATOS REVISADOS (Contiene nuestro excel con la revision realizada y los archivos debidamente filtrados)
3.DATOS PROCESADOS 

Se encuentra listo para el procesamiento @AngeloValenzuelaP

**Comment by Anamontesf** [comment]
Continuamos a la espera de la entrega de este tablero para revision @HelmuthRaddatz

**Comment by HelmuthRaddatz** [comment]
Se han subido todos los dashboard con 34 vehículos procesados.

Los tableros se pueden ver en: https://public.tableau.com/app/profile/hdl.bimbo/vizzes

@Anamontesf @camilafcubillos @AngeloValenzuelaP

**Comment by Anamontesf** [comment]
Se hizo la respectiva revisión y no se encontraron los datos del 2022, unicamente se encuentran los datos del 2021. 

Adicionalmente se requiere el archivo de trazabilidad del procesamiento @HelmuthRaddatz

**Comment by AngeloValenzuelaP** [comment]
Hola @Anamontesf espero que este bien.

Escribo lo siguiente para comentar los siguientes puntos:

1) El archivo de trazabilidad que generaba Eduardo fue iniciativa propia de el, mas no un proceso interno del CTL.
2) Algunos tableros, sobre todos los con exceso de data, solo muestran la data mas actual debido a las limitancias de tableau public. para levantar un tablero con toda la info, ej Cemex, es necesario Tableau server que es de pago. 
3) Ya se cumplieron todos los procesamientos dentro del periodo acordado, es decir, hasta Febrero de este año.
4) Para continuar el trabajo conjunto es necesario que se generen nuevos acuerdos con nuestros directivos.

Saludos cordiales 
Angelo Valenzuela.

**Comment by camilafcubillos** [comment]
Estimado Angelo y estimado Helmuth @AngeloValenzuelaP @HelmuthRaddatz 

1. La iniciativa no fue por parte de Eduardo fue un acuerdo que se tenía con el fin de levantar estadísticas, dado que es el seguimiento que se pautó para poder analizar de manera más detallada que en efecto los tableros si respondieran con la información analizada. Lo cual no se está evidenciando dado los múltiples errores, fallas y/o falta de información que los mismos presentan. 
2. ⁠lo pedido es lo pactado desde el mes de noviembre, no se está pidiendo análisis adicionales de están pidiendo análisis los cuales se tienen desde noviembre y todo lo que debe entregar la UNAB conforme los acuerdos con el proyecto son hasta marzo del 2024, fecha donde tiene fin el proyecto, y fecha y acuerdo que se pagó a UNAB. Recordar que son temas pendientes más no nuevos procesos. 
3. ⁠aclarar que no se necesitan nuevos acuerdos dado que son errores o tableros que no están completos desde noviembre, tener en cuenta NO SON nuevos procesamientos son temas PENDIENTES por parte de UNAB. Conforme la reunión que se tuvo anteriormente se tenía eso claro, no veo la razón de decir que se necesitan nuevos acuerdos si los procesamientos son pendientes por lado de ustedes. 

Saludos y sin embargo, si no hay solución, mejor recurrir a gordon y julio con el fin de corroborar todo en reunión, para no tener mal entendidos y generar situaciones incómodas.

**Comment by HelmuthRaddatz** [comment]
Estimada @Anamontesf, la estadística de esta empresa según lo procesado por @AngeloValenzuelaP es la siguiente:
![image](https://github.com/user-attachments/assets/da3fbfb5-fcc6-43a2-9894-ee3ebee54c64)

Los vehículos son:
Patente

1. EQQ146
2. EQQ147
3. EQQ512
4. EYX268
5. EYX269
6. EYX270
7. FSU645
8. GES354
9. GES885
10. GET092
11. JKU154
12. JKU155
13. JOV748
14. KUS174
15. SPX262
16. SPX542
17. SZO919
18. SZU071
19. TFT885
20. TGK918
21. THX234
22. THX516
23. TSW554
24. TSX022
25. TTG278
26. UPP754
27. VAK219
28. WCR949
29. WFV934
30. WGZ690
31. WGZ695
32. WMZ113
33. WNM271
34. WNY780
